### PR TITLE
Fix duplicate inputs for img

### LINKED ISSUE #264: [PE-D][Tester B] Add Command - Multiple images accepted via CLI
**Description** 
Multiple consecutive image uploads are allowed at once when it should throw an invalid format error as indicated by UG command format.

**Steps to reproduce** 
add n/testingthisagain img//Users/username/Desktop/Filepath.png img//Users/username/Desktop/Filepath.png

**Expected** 
Error thrown

**Actual** 
Adds the contact successfully 

**Screenshots**

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: basil-boh/ped#12

### PR DESCRIPTION
**Pull request by nictjh**
Resolves #264

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 1]
```diff
@@ -56,7 +56,7 @@ public AddCommand parse(String args) throws ParseException {
         }
 
         argMultimap.verifyNoDuplicatePrefixesFor(PREFIX_NAME, PREFIX_PHONE, PREFIX_EMAIL, PREFIX_ADDRESS,
-                PREFIX_RELATIONSHIP, PREFIX_BIRTHDAY, PREFIX_NICKNAME, PREFIX_NOTES);
+                PREFIX_RELATIONSHIP, PREFIX_BIRTHDAY, PREFIX_NICKNAME, PREFIX_NOTES, PREFIX_IMG);
```
Comment (Benjam11n) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java:59]: Very good inclusion

**Review by Benjam11n — APPROVED** [review]
LGTM
